### PR TITLE
Upgrade to the latest operator-sdk

### PR DESCRIPTION
**Pull request by mprahl**
operator-sdk v1.x now wraps Kubebuilder for its scaffolding and code
generation. This changes the path of `./cmd/manager/main.go` to
`.main.go` and `./pkg/apis/policies/v1` to `./apis/policy/v1`.

The controller paths are also different when initializing a new project,
however, since manifest generation by Kubebuilder is not used in this
project, the old paths were kept.

The largest changes stem from updating the underlying Kubernetes Go
modules as some APIs changed or were removed.

It's also important to note that operator-sdk is no longer a Go module
dependency and because a couple small functions from that are used in
this project, those were copied over, mostly unmodified.

### CODE REVIEW

**Comment by mprahl** [comment]
I filed this PR to hopefully fix the permission denied error coming from Prow:
https://github.com/openshift/release/pull/20825

**Review by gparvin — APPROVED** [review]
Super nice!

**Pull request merged**
